server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 300000
          starttls:
            enable: true
    verify-link: "http://localhost:5173/auth/verify-email?link="
  #redis
  data:
    redis:
      host: localhost
      port: 6379

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 1234
    driver-class-name:
logging:
  level:
    org:
      hibernate: info

cloud:
  aws:
    credentials:
      access-key: AKIATHBNGYVRJ2CC2WE7
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false
    s3:
      bucket: tiary-images

batch:
  server:
    url: http://localhost:8089

jwt:
  issuer: tiary
  secret: 2-tiary
