server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.H2Dialect
  #    defer-datasource-initialization: true
  #  sql:
  #    init:
  #      data-locations: classpath:data.sql
  #      mode: always

  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password: 1234
    driver-class-name:
logging:
  level:
    org:
      hibernate: info